# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFhFxFikN338QAsBuOUtBEUH31V2yOHI
"""

# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Load the data
data = pd.read_csv('wdbc.data', header=None)

# Assign features and target
# Assuming the first column is ID, the second column is the label, and the rest are features
X = data.iloc[:, 2:]  # Features
y = data.iloc[:, 1]   # Target labels (M = malignant, B = benign)

# Encode the categorical data
y = y.map({'M': 1, 'B': 0})

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Instantiate the model
model = SVC(kernel='linear')  # You can also try other kernels like 'rbf'

# Train the model
model.fit(X_train, y_train)

# Predictions
predictions = model.predict(X_test)

# Evaluate the model
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))